spring:
  application:
    name: ms-lib-registry-server

server:
  port: 8761

eureka:
  instance:
    hostname: registry-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://registry-server:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000

logging:
  level:
    root: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
