spring:
  application:
    name: ms-lib-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
        bootstrap: true
  profiles:
    active: native

server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://registry-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.cloud.config: INFO
